### ISSUE TITLE
Bluetooth Pin Pairing

### ISSUE THREAD

**Issue by skygamer125** [canonical/bluez.dart#68] opened 2022-01-27 18:50 UTC
How can I pair with a specific code?....

I have been trying to figure out... no examples exist for connecting to a device and using a pin code or something...

I need to connect my phone with my raspberry pi, and this library seemed to be the unique one capable of assisting me in linux... But If i cant use a code (the one that appears on my phone) to verify and pair it... then I really wont be able to do anything with it...

I don't know if this library can / cant do this.... at this point in time... but I really wish there is a way... that at least I'm unaware of, otherwise i don't know what to do.

Functionalities I'm wondering if they exist:

- Setting up a Pin for Pairing (changing the pin)
- Pairing with a PIN... so it can verify the device that it is connecting to.

**Comment by skygamer125** [comment] 2022-01-27 18:59
Oh, and
- Listening for a device "pairing"

if a device tries to pair, be able to listen to it and execute a function
(I have no idea if this exists or not..)

**Comment by robert-ancell** [comment] 2022-02-02 03:23
This requires https://github.com/canonical/bluez.dart/issues/41 to be implemented. So should be possible, but not yet supported.

**Comment by skygamer125** [comment] 2022-02-02 03:25
Alright, well,  Till then, I have no idea of any other library to use than to be able to proceed with the making of my application with Flutter - dart.

Is this library able to send and receive data over Bluetooth aswell? I have been having a really hard time to understand it's current capabilities. what it can and cant do...

**Comment by skygamer125** [comment] 2022-02-02 03:27
for example, am I able to send HID commands like I would with a Bluetooth keyboard? or is it possible to send and receive any data at all?

**Comment by skygamer125** [comment] 2022-02-02 03:27
thank you very much for your time in any situation! its really appreciated!

**Comment by robert-ancell** [comment] 2022-02-03 00:59
There is basic sending and receiving of data. The [BlueZ GATT documentation](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/gatt-api.txt) might help you see how to use BlueZ to do this.

You best current options are probably:
- Use the BlueZ D-Bus API directly to access any features not currently implemented in this project.
- Do PRs for any features you require that are missing.

Hope this helps!

**Comment by Feichtmeier** [comment] 2022-02-22 11:17
@robert-ancell do understand this better

it is disabled by default here https://github.com/canonical/bluez.dart/blob/main/lib/src/bluez_client.dart#L906
because the the bluez demon itself does not have this feature yet?

Is GCC sending the dbus method rather than using the bluez client?
Thanks in advance

**Comment by robert-ancell** [comment] 2022-02-22 21:46
@Feichtmeier `allowInteractiveAuthorization` refers to BlueZ being allowed to use Polkit to authorize requests. That probably should be true by default - it is only useful as false if you are making some script that can't be interactive.

**Comment by Feichtmeier** [comment] 2022-02-22 21:48
> @Feichtmeier `allowInteractiveAuthorization` refers to BlueZ being allowed to use Polkit to authorize requests. That probably should be true by default - it is only useful as false if you are making some script that can't be interactive.

woops, sorry for misunderstooding. I was looking into the Gatt service thing but I guess I need some more time. I think I got the rest of the API in settings now

**Comment by robert-ancell** [comment] 2022-03-07 02:16
Closing duplicate of https://github.com/canonical/bluez.dart/issues/41

**Closed by robert-ancell** 2022-03-07 02:16 UTC
